repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=10000']
    language_version: python3
  - id: check-ast
  - id: check-json

# automatically upgrade Python syntax to newer versions
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
    - id: pyupgrade
      args: [ --py36-plus ]

# reorder and organize Python import statements
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
    - id: reorder-python-imports
      args: [ --py36-plus ]

# widely-used code formatter for Python that automatically formats code to adhere to a consistent style
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
  
# check code against a set of style and linting rules
- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    language_version: python3
    # additional_dependencies: [flake8-docstrings]
    args: [--max-line-length=120]

# static type checker for Python that helps catch type-related errors before runtime
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  - id: mypy

# format Markdown files to ensure consistent and readable Markdown
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
  
# various code quality checks and formatting to Jupyter Notebooks
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.1
  hooks:
    - id: nbqa-isort
    - id: nbqa-black
    - id: nbqa-mypy
    - id: nbqa-flake8

# remove the output cells from Jupyter Notebooks
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.0
  hooks:
  - id: nbstripout
